# Generated by Django 2.0.7 on 2018-07-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_directed', models.BooleanField()),
                ('type_of_edge', models.CharField(choices=[('derives_from', 'Derives from'), ('symbol_of', 'Symbol of'), ('compound_of', 'Compound of')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('tr', 'Turkish'), ('fr', 'French'), ('gr', 'German'), ('pl', 'Polish'), ('kr', 'Kurdish'), ('lt', 'Latin'), ('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='dictionary.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='dictionary.Node'),
        ),
    ]
